Rails.application.routes.draw do
  root "static_pages#index"
  get "static_pages/compair"
  get "static_pages/components"
  get "static_pages/contact"
  get "static_pages/faq"
  get "static_pages/forgetpass"
  get "static_pages/legal_notice"
  get "static_pages/login"
  get "static_pages/normal"
  get "static_pages/product_details"
  get "static_pages/products"
  get "static_pages/product_summary"
  get "static_pages/register"
  get "static_pages/special_offer"
  get "static_pages/tac"
end
